// Suggested user.js generated by firefox_full_performance_hud_autotune.sh
// Adjusted based on live Firefox metrics

user_pref("javascript.options.mem.max", 4105);;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
user_pref("dom.timeout.background_throttling_max_budget", 3000);;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
user_pref("dom.min_background_timeout_value", 500);;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
user_pref("gfx.webrender.enable-gpu-thread", false);;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
user_pref("browser.sessionstore.interval", 30000);;;;;;
